name: localizy
description: A simple Dart-based localization generator that converts your JSON locale files into a strongly-typed strings.dart file with camelCase getters and safe normalized keys.
version: 1.0.2
homepage: https://github.com/IbrahimKhatrii/localizy

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # flutter:
  #   sdk: flutter
  path: ^1.9.0
  glob: ^2.1.2
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

executables:
  generate: generate
